apiKey = "AIzaSyBoP53OTUEcrY6TVAF6DE3KQEb2r4WfT7I"
authDomain = "pdf-editing-tool.firebaseapp.com"
projectId = "pdf-editing-tool"
storageBucket = "pdf-editing-tool.firebasestorage.app"
messagingSenderId = "918924033221"
appId = "1:918924033221:web:d8b51df3363016121f84ac"
measurementId = "G-88E0R9PKBQ"
databaseURL = "https://console.firebase.google.com/u/0/project/pdf-editing-tool/database/pdf-editing-tool-default-rtdb/data/~2F"
